name: Flow Control
pname: flow_control
description: Coded Flows logic control bricks
version: 0.1.1
icon: hierarchy
private: false
base: true
category: base_flow_management
python:
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12'
